# Generated by Django 3.0.3 on 2020-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default='blogger', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogger',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
