# Generated by Django 3.0.3 on 2020-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('option_one', models.CharField(max_length=20)),
                ('option_two', models.CharField(max_length=20)),
                ('option_three', models.CharField(max_length=20)),
                ('option_count_one', models.IntegerField(default=0)),
                ('option_count_two', models.IntegerField(default=0)),
                ('option_count_three', models.IntegerField(default=0)),
            ],
        ),
    ]
