# Generated by Django 3.0.3 on 2020-04-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createvote',
            new_name='Poll',
        ),
    ]
